In [29]:
import numpy as np
import pandas as pd

In [42]:
def load_data(file_path):
    """
    Load a CSV dataset and return a pandas DataFrame.

    Parameters:
        file_path (str): Relative path to the CSV file.

    Returns:
        pandas.DataFrame
    """
    return pd.read_csv(file_path)

# Load dataset
df = load_data("../data/raw/loan_approval_dataset.csv")

# Display first five rows
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [31]:
# =========================================
# Dataset Overview
# =========================================

# Shape
print(df.shape)
print()

# head()
print(df.head(5).to_string())
print()

# tail()
print(df.tail(5).to_string())
print()

# sample()
print(df.sample().to_string())

(4269, 13)

   loan_id   no_of_dependents      education  self_employed   income_annum   loan_amount   loan_term   cibil_score   residential_assets_value   commercial_assets_value   luxury_assets_value   bank_asset_value  loan_status
0        1                  2       Graduate             No        9600000      29900000          12           778                    2400000                  17600000              22700000            8000000     Approved
1        2                  0   Not Graduate            Yes        4100000      12200000           8           417                    2700000                   2200000               8800000            3300000     Rejected
2        3                  3       Graduate             No        9100000      29700000          20           506                    7100000                   4500000              33300000           12800000     Rejected
3        4                  3       Graduate             No        8200000      30700000           8           467                   18200000                   3300000              23300000            7900000     Rejected
4        5                  5   Not Graduate            Yes        9800000      24200000          20           382                   12400000                   8200000              29400000            5000000     Rejected

      loan_id   no_of_dependents      education  self_employed   income_annum   loan_amount   loan_term   cibil_score   residential_assets_value   commercial_assets_value   luxury_assets_value   bank_asset_value  loan_status
4264     4265                  5       Graduate            Yes        1000000       2300000          12           317                    2800000                    500000               3300000             800000     Rejected
4265     4266                  0   Not Graduate            Yes        3300000      11300000          20           559                    4200000                   2900000              11000000            1900000     Approved
4266     4267                  2   Not Graduate             No        6500000      23900000          18           457                    1200000                  12400000              18100000            7300000     Rejected
4267     4268                  1   Not Graduate             No        4100000      12800000           8           780                    8200000                    700000              14100000            5800000     Approved
4268     4269                  1       Graduate             No        9200000      29700000          10           607                   17800000                  11800000              35700000           12000000     Approved

      loan_id   no_of_dependents      education  self_employed   income_annum   loan_amount   loan_term   cibil_score   residential_assets_value   commercial_assets_value   luxury_assets_value   bank_asset_value  loan_status
2416     2417                  2   Not Graduate            Yes        1200000       2900000          12           330                     400000                   1600000               3800000             600000     Rejected

In [32]:
# =========================================
# Dataset Structure
# =========================================

# columns
print(df.columns.tolist())
print()

# info()
print(df.info())
print()

# dtypes
print(df.dtypes)

['loan_id', ' no_of_dependents', ' education', ' self_employed', ' income_annum', ' loan_amount', ' loan_term', ' cibil_score', ' residential_assets_value', ' commercial_assets_value', ' luxury_assets_value', ' bank_asset_value', ' loan_status']

<class 'pandas.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   str
 3    self_employed             4269 non-null   str
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   str
dtypes: int64(10), str(3)
memory usage: 433.7 KB
None

loan_id                      int64
 no_of_dependents            int64
 education                     str
 self_employed                 str
 income_annum                int64
 loan_amount                 int64
 loan_term                   int64
 cibil_score                 int64
 residential_assets_value    int64
 commercial_assets_value     int64
 luxury_assets_value         int64
 bank_asset_value            int64
 loan_status                   str
dtype: object

In [33]:
# =========================================
# Dataset Structure
# =========================================

# Statistical Summary

print(df.describe().to_string())
print()

# describe(include="object")

print(df.describe(include="object"))

           loan_id   no_of_dependents   income_annum   loan_amount    loan_term   cibil_score   residential_assets_value   commercial_assets_value   luxury_assets_value   bank_asset_value
count  4269.000000        4269.000000   4.269000e+03  4.269000e+03  4269.000000   4269.000000               4.269000e+03              4.269000e+03          4.269000e+03       4.269000e+03
mean   2135.000000           2.498712   5.059124e+06  1.513345e+07    10.900445    599.936051               7.472617e+06              4.973155e+06          1.512631e+07       4.976692e+06
std    1232.498479           1.695910   2.806840e+06  9.043363e+06     5.709187    172.430401               6.503637e+06              4.388966e+06          9.103754e+06       3.250185e+06
min       1.000000           0.000000   2.000000e+05  3.000000e+05     2.000000    300.000000              -1.000000e+05              0.000000e+00          3.000000e+05       0.000000e+00
25%    1068.000000           1.000000   2.700000e+06  7.700000e+06     6.000000    453.000000               2.200000e+06              1.300000e+06          7.500000e+06       2.300000e+06
50%    2135.000000           3.000000   5.100000e+06  1.450000e+07    10.000000    600.000000               5.600000e+06              3.700000e+06          1.460000e+07       4.600000e+06
75%    3202.000000           4.000000   7.500000e+06  2.150000e+07    16.000000    748.000000               1.130000e+07              7.600000e+06          2.170000e+07       7.100000e+06
max    4269.000000           5.000000   9.900000e+06  3.950000e+07    20.000000    900.000000               2.910000e+07              1.940000e+07          3.920000e+07       1.470000e+07

        education self_employed loan_status
count        4269          4269        4269
unique          2             2           2
top      Graduate           Yes    Approved
freq         2144          2150        2656

C:\Users\athish\AppData\Local\Temp\ipykernel_24732\2622912620.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include="object"))

In [34]:
# =========================================
# Data Quality Inspection
# =========================================


# Check Missing Values

print(df.isnull().sum())

#missing_values = pd.DataFrame({
#    "Missing Values": df.isnull().sum(),
#    "Percentage" : (df.isnull().sum()/len(df))*100
#})
#print(missing_values)

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [35]:
# Check Duplicate Records

print(df.duplicated().sum())

# If duplicates exist
df[df.duplicated()]

0

Empty DataFrame
Columns: [loan_id,  no_of_dependents,  education,  self_employed,  income_annum,  loan_amount,  loan_term,  cibil_score,  residential_assets_value,  commercial_assets_value,  luxury_assets_value,  bank_asset_value,  loan_status]
Index: []

In [36]:
# Check Data Types

df.info()
# print(df.dtypes)

<class 'pandas.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   str
 3    self_employed             4269 non-null   str
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   str
dtypes: int64(10), str(3)
memory usage: 433.7 KB

In [37]:
# Inspect Column Names
print(df.columns)

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='str')

In [38]:
# Check Unique Values in Categorical Columns

Categorical_Columns = df.select_dtypes(include="object").columns
print(Categorical_Columns)

# inspect them
for col in Categorical_Columns:
    print("="*50)
    print(col)
    print(df[col].value_counts())

Index([' education', ' self_employed', ' loan_status'], dtype='str')
==================================================
 education
 education
Graduate        2144
Not Graduate    2125
Name: count, dtype: int64
==================================================
 self_employed
 self_employed
Yes    2150
No     2119
Name: count, dtype: int64
==================================================
 loan_status
 loan_status
Approved    2656
Rejected    1613
Name: count, dtype: int64

C:\Users\athish\AppData\Local\Temp\ipykernel_24732\3681503331.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  Categorical_Columns = df.select_dtypes(include="object").columns

In [39]:
# Check Cardinality

for col in Categorical_Columns:
    print(f"{col} : {df[col].nunique()} unique values")

 education : 2 unique values
 self_employed : 2 unique values
 loan_status : 2 unique values

In [40]:
# Memory Usage
df.memory_usage(deep=True)

Index                           132
loan_id                       34152
 no_of_dependents             34152
 education                   256102
 self_employed               224138
 income_annum                 34152
 loan_amount                  34152
 loan_term                    34152
 cibil_score                  34152
 residential_assets_value     34152
 commercial_assets_value      34152
 luxury_assets_value          34152
 bank_asset_value             34152
 loan_status                 247602
dtype: int64

In [41]:
# =========================================
# Table Summary
# =========================================

summary = pd.DataFrame({
    "Data Type" : df.dtypes,
    "Missing Values" : df.isnull().sum(),
    "Unique Values" : df.nunique()
})
print(summary)

                          Data Type  Missing Values  Unique Values
loan_id                       int64               0           4269
 no_of_dependents             int64               0              6
 education                      str               0              2
 self_employed                  str               0              2
 income_annum                 int64               0             98
 loan_amount                  int64               0            378
 loan_term                    int64               0             10
 cibil_score                  int64               0            601
 residential_assets_value     int64               0            278
 commercial_assets_value      int64               0            188
 luxury_assets_value          int64               0            379
 bank_asset_value             int64               0            146
 loan_status                    str               0              2